function About({lang}) {
    return(
        <div>
            <h1>{lang === 'en' ? 'About Me Page' : 'Hakkımda Sayfası'}</h1>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod, fugit voluptatum minus suscipit aperiam eveniet ratione, autem odio modi placeat odit doloribus officia. Voluptatibus doloremque ullam sunt nulla, officiis odit perferendis corrupti voluptate beatae sint. Ea mollitia vel nam repellendus quasi incidunt deserunt aperiam ab neque nostrum at ratione temporibus voluptatibus nisi debitis dolorem delectus deleniti officiis recusandae reiciendis, aliquam saepe quibusdam aspernatur nobis? Distinctio esse illo dolor dolore amet animi, quibusdam ad a placeat pariatur veritatis perspiciatis molestiae unde illum sequi eaque odio enim soluta quidem recusandae deleniti voluptatum dicta ipsum? Debitis recusandae eos omnis deserunt suscipit perferendis nam doloremque consequuntur? Vitae doloribus aspernatur repellendus accusantium libero magnam esse! Quo saepe vitae, voluptatum quisquam quas quia alias id accusamus modi molestias vero placeat totam eligendi quae maxime at voluptas asperiores odio magnam eveniet mollitia? Voluptas, repellat qui ex ab velit ea, tempora aperiam atque quisquam magni aliquam, dolor quas dolorem cum! Molestias laborum maxime porro, nisi iste atque eos voluptas est id quidem. A hic reprehenderit expedita rem praesentium, minima ex, vero error sapiente magni dolorem voluptatum dolorum facilis cumque qui molestias ullam maiores laboriosam. Aperiam id dolorem tempore velit maiores eius labore cum vel libero nemo! Nobis, vero perspiciatis aliquam odit neque magnam tenetur aut eligendi quaerat omnis voluptate voluptatibus doloribus aliquid illum repellat placeat perferendis tempore sunt laudantium hic nulla cupiditate culpa veniam nesciunt. Dolores, exercitationem. Dicta tempore ea voluptates sed odio beatae nulla qui, amet, magnam rerum temporibus? Mollitia totam fuga facilis sequi nihil nisi quia. Voluptates minima hic est quos, ut accusamus commodi, natus molestias recusandae officia ipsam quae dolorum dicta earum qui id explicabo consequuntur voluptatum nostrum vel voluptatibus omnis. Numquam consectetur nesciunt rerum veniam nisi adipisci minima labore eaque velit atque officia temporibus quasi totam sequi molestias sint, mollitia error non dolor est?</p>
        </div>
    );
}


export default About;